// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoxvuizjjggarhhyhlsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVveHZ1aXpqamdnYXJoaHlobHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjU4NDksImV4cCI6MjA2MjA0MTg0OX0.a3XQfJDCWrhIR-BJ-HIZmYpgX9yUJxPbrhMuOD09gsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);